export {
  TOOLS_PRINTER_OFFLINE_MESSAGE,
  TOOLS_SENIAT_OFFLINE_MESSAGE,
  TOOLS_PRINTER_STATUS_TIMEOUT_MESSAGE,
  TOOLS_PRINTER_STATUS_TIMEOUT_MS,
  areToolsRemoteActionsDisabled,
  areToolsRemoteActionsEnabled,
  areToolsSeniatActionsDisabled,
  areToolsSeniatActionsEnabled,
  getToolsConnectionIssue,
  hasUsableToolsNetworkInfo,
  isToolsPrinterConnectionKnown,
  isToolsPrinterConnectionResolved,
  isToolsPrinterOnline,
  isToolsPrinterReachable,
  isToolsSeniatOnline,
  isUsableToolsNetworkField,
  resolveToolsPrinterNetworkInfo,
  type ToolsConnectionIssue,
} from "@/lib/tools-printer-connection";
